--
-- PostgreSQL database dump
--

\restrict cu0DgKDOSWUUdckZ0ATXIM5uGx3PYodiIEUiJa2e7gS1gHAj4pAixDeZ77Wlqyv

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: aichat_assistantmessage; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.aichat_assistantmessage (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    session_id bigint NOT NULL
);


ALTER TABLE public.aichat_assistantmessage OWNER TO usuario_django;

--
-- Name: aichat_assistantmessage_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.aichat_assistantmessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aichat_assistantmessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aichat_assistantsession; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.aichat_assistantsession (
    id bigint NOT NULL,
    session_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.aichat_assistantsession OWNER TO usuario_django;

--
-- Name: aichat_assistantsession_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.aichat_assistantsession ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aichat_assistantsession_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO usuario_django;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO usuario_django;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO usuario_django;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comunication_conversation; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.comunication_conversation (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    buyer_id bigint NOT NULL,
    owner_id bigint NOT NULL,
    property_id bigint NOT NULL
);


ALTER TABLE public.comunication_conversation OWNER TO usuario_django;

--
-- Name: comunication_conversation_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.comunication_conversation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comunication_conversation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comunication_message; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.comunication_message (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_read boolean NOT NULL,
    conversation_id bigint NOT NULL,
    sender_id bigint NOT NULL
);


ALTER TABLE public.comunication_message OWNER TO usuario_django;

--
-- Name: comunication_message_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.comunication_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comunication_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO usuario_django;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO usuario_django;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO usuario_django;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO usuario_django;

--
-- Name: properties_property; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.properties_property (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    address character varying(255) NOT NULL,
    city character varying(100) NOT NULL,
    price numeric(12,0) NOT NULL,
    listing_type character varying(20) NOT NULL,
    rooms smallint NOT NULL,
    bathrooms smallint NOT NULL,
    square_meters integer,
    capacity smallint NOT NULL,
    image character varying(100),
    image_url character varying(1000) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    owner_id bigint,
    availability_dates character varying(255) NOT NULL,
    latitude numeric(9,6),
    longitude numeric(9,6),
    CONSTRAINT properties_property_bathrooms_check CHECK ((bathrooms >= 0)),
    CONSTRAINT properties_property_capacity_check CHECK ((capacity >= 0)),
    CONSTRAINT properties_property_rooms_check CHECK ((rooms >= 0)),
    CONSTRAINT properties_property_square_meters_check CHECK ((square_meters >= 0))
);


ALTER TABLE public.properties_property OWNER TO usuario_django;

--
-- Name: properties_property_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.properties_property ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.properties_property_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: properties_savedproperty; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.properties_savedproperty (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    property_obj_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.properties_savedproperty OWNER TO usuario_django;

--
-- Name: properties_savedproperty_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.properties_savedproperty ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.properties_savedproperty_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions_booking; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.transactions_booking (
    id bigint NOT NULL,
    check_in date NOT NULL,
    check_out date NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    property_id bigint NOT NULL,
    user_id bigint NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.transactions_booking OWNER TO usuario_django;

--
-- Name: transactions_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.transactions_booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions_purchase; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.transactions_purchase (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    total_value numeric(12,2) NOT NULL,
    status character varying(20) NOT NULL,
    buyer_id bigint NOT NULL,
    property_id bigint NOT NULL
);


ALTER TABLE public.transactions_purchase OWNER TO usuario_django;

--
-- Name: transactions_purchase_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.transactions_purchase ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_purchase_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_client; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.users_client (
    id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.users_client OWNER TO usuario_django;

--
-- Name: users_client_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.users_client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_owner; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.users_owner (
    id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.users_owner OWNER TO usuario_django;

--
-- Name: users_owner_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.users_owner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_owner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(15),
    registration_date timestamp with time zone NOT NULL
);


ALTER TABLE public.users_user OWNER TO usuario_django;

--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO usuario_django;

--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: usuario_django
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO usuario_django;

--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: usuario_django
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: aichat_assistantmessage; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.aichat_assistantmessage (id, role, content, created_at, session_id) FROM stdin;
\.


--
-- Data for Name: aichat_assistantsession; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.aichat_assistantsession (id, session_id, created_at, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	8	add_user
22	Can change user	8	change_user
23	Can delete user	8	delete_user
24	Can view user	8	view_user
25	Can add client	6	add_client
26	Can change client	6	change_client
27	Can delete client	6	delete_client
28	Can view client	6	view_client
29	Can add owner	7	add_owner
30	Can change owner	7	change_owner
31	Can delete owner	7	delete_owner
32	Can view owner	7	view_owner
33	Can add property	9	add_property
34	Can change property	9	change_property
35	Can delete property	9	delete_property
36	Can view property	9	view_property
37	Can add saved property	10	add_savedproperty
38	Can change saved property	10	change_savedproperty
39	Can delete saved property	10	delete_savedproperty
40	Can view saved property	10	view_savedproperty
41	Can add contract	12	add_contract
42	Can change contract	12	change_contract
43	Can delete contract	12	delete_contract
44	Can view contract	12	view_contract
45	Can add booking	11	add_booking
46	Can change booking	11	change_booking
47	Can delete booking	11	delete_booking
48	Can view booking	11	view_booking
49	Can add conversation	13	add_conversation
50	Can change conversation	13	change_conversation
51	Can delete conversation	13	delete_conversation
52	Can view conversation	13	view_conversation
53	Can add message	14	add_message
54	Can change message	14	change_message
55	Can delete message	14	delete_message
56	Can view message	14	view_message
57	Can add assistant message	15	add_assistantmessage
58	Can change assistant message	15	change_assistantmessage
59	Can delete assistant message	15	delete_assistantmessage
60	Can view assistant message	15	view_assistantmessage
61	Can add assistant session	16	add_assistantsession
62	Can change assistant session	16	change_assistantsession
63	Can delete assistant session	16	delete_assistantsession
64	Can view assistant session	16	view_assistantsession
65	Can add purchase	17	add_purchase
66	Can change purchase	17	change_purchase
67	Can delete purchase	17	delete_purchase
68	Can view purchase	17	view_purchase
\.


--
-- Data for Name: comunication_conversation; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.comunication_conversation (id, created_at, updated_at, buyer_id, owner_id, property_id) FROM stdin;
4	2026-05-19 20:39:01.065945+00	2026-05-19 20:39:01.065953+00	15	5	11
\.


--
-- Data for Name: comunication_message; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.comunication_message (id, content, created_at, is_read, conversation_id, sender_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
7	2026-05-19 20:23:19.011578+00	11	lauramarin452@gmail.com	3		8	15
8	2026-05-19 20:23:49.669224+00	14	sebasrua@gmail.com	3		8	15
9	2026-05-19 20:23:49.669247+00	13	sag.arangog@gmail.com	3		8	15
10	2026-05-19 20:23:49.669257+00	12	lmarinvelez0@gmail.com	3		8	15
11	2026-05-19 20:28:53.953878+00	12	Apt Moderno |A pie Zona Rosa, Cafés y Restaurantes - Dosquebradas	2	[{"changed": {"fields": ["Image"]}}]	9	15
12	2026-05-19 20:30:11.569582+00	11	Apartamento nuevo tipo loft #8 cabecera - Perímetro Urbano Bucaramanga	2	[{"changed": {"fields": ["Image"]}}]	9	15
13	2026-05-19 20:31:09.931365+00	10	Aparta Hotel en San Gil - San Gil	2	[{"changed": {"fields": ["Image"]}}]	9	15
14	2026-05-19 20:31:44.207983+00	9	Atardecer llanero - Villanueva	2	[{"changed": {"fields": ["Image"]}}]	9	15
15	2026-05-19 20:32:00.863951+00	10	Aparta Hotel en San Gil - San Gil	2	[{"changed": {"fields": ["Image"]}}]	9	15
16	2026-05-19 20:33:25.119355+00	16	lmarinvelez@gmail.com	1	[{"added": {}}]	8	15
17	2026-05-19 20:34:00.060497+00	16	lmarinvelez@gmail.com	2	[]	8	15
18	2026-05-19 20:34:10.776512+00	16	lmarinvelez@gmail.com	3		8	15
19	2026-05-19 20:36:59.930524+00	8	D603-Estudio Con Excelente Ubicación - Perímetro Urbano Barranquilla	2	[{"changed": {"fields": ["Owner", "Image"]}}]	9	15
20	2026-05-19 20:37:25.732399+00	7	Escapada con estilo a Santa Teresita – Corazón de Cali - Cali ciudad	2	[{"changed": {"fields": ["Owner", "Image"]}}]	9	15
21	2026-05-19 20:37:48.721838+00	6	Cabaña de lujo con jacuzzi Malbec-La Cava Lodge - Medellín	2	[{"changed": {"fields": ["Owner", "Image"]}}]	9	15
22	2026-05-19 20:38:23.844985+00	5	Hotel/Aeropuerto/Desayuno/Embajada/T. Buses/AV 26 - Bogotá	2	[{"changed": {"fields": ["Owner", "Image"]}}]	9	15
23	2026-05-19 20:45:38.505832+00	4	Casa Serena - Perímetro Urbano Medellín	2	[{"changed": {"fields": ["Image"]}}]	9	15
24	2026-05-19 20:45:50.246131+00	4	Casa Serena - Perímetro Urbano Medellín	2	[{"changed": {"fields": ["Owner"]}}]	9	15
25	2026-05-19 20:46:04.394104+00	3	Cabaña F2 Rodadero S. Marta - Perímetro Urbano Santa Marta	2	[{"changed": {"fields": ["Owner", "Image"]}}]	9	15
26	2026-05-19 20:46:19.233904+00	2	cogedora Suite, vista al océano en Cartagena 921 - Cartagena de Indias	2	[{"changed": {"fields": ["Owner", "Image"]}}]	9	15
27	2026-05-19 20:47:22.677311+00	1	Acogedora Suite, vista al océano en Cartagena 921 - Cartagena de Indias	2	[{"changed": {"fields": ["Owner", "Image"]}}]	9	15
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	users	client
7	users	owner
8	users	user
9	properties	property
10	properties	savedproperty
11	transactions	booking
12	transactions	contract
13	comunication	conversation
14	comunication	message
15	aichat	assistantmessage
16	aichat	assistantsession
17	transactions	purchase
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-27 21:28:54.405532+00
2	contenttypes	0002_remove_content_type_name	2026-04-27 21:28:54.408451+00
3	auth	0001_initial	2026-04-27 21:28:54.42979+00
4	auth	0002_alter_permission_name_max_length	2026-04-27 21:28:54.432395+00
5	auth	0003_alter_user_email_max_length	2026-04-27 21:28:54.434983+00
6	auth	0004_alter_user_username_opts	2026-04-27 21:28:54.436823+00
7	auth	0005_alter_user_last_login_null	2026-04-27 21:28:54.44961+00
8	auth	0006_require_contenttypes_0002	2026-04-27 21:28:54.450349+00
9	auth	0007_alter_validators_add_error_messages	2026-04-27 21:28:54.452403+00
10	auth	0008_alter_user_username_max_length	2026-04-27 21:28:54.454297+00
11	auth	0009_alter_user_last_name_max_length	2026-04-27 21:28:54.456362+00
12	auth	0010_alter_group_name_max_length	2026-04-27 21:28:54.458618+00
13	auth	0011_update_proxy_permissions	2026-04-27 21:28:54.460756+00
14	auth	0012_alter_user_first_name_max_length	2026-04-27 21:28:54.463491+00
15	users	0001_initial	2026-04-27 21:28:54.490989+00
16	admin	0001_initial	2026-04-27 21:28:54.500519+00
17	admin	0002_logentry_remove_auto_add	2026-04-27 21:28:54.503488+00
18	admin	0003_logentry_add_action_flag_choices	2026-04-27 21:28:54.506301+00
19	properties	0001_initial	2026-04-27 21:28:54.509836+00
20	properties	0002_initial	2026-04-27 21:28:54.515232+00
21	properties	0003_property_availability_dates	2026-04-27 21:28:54.518689+00
22	properties	0004_alter_property_options_booking	2026-04-27 21:28:54.529653+00
23	properties	0005_availability	2026-04-27 21:28:54.537703+00
24	properties	0006_rename_date_availability_availability_dates_and_more	2026-04-27 21:28:54.543271+00
25	properties	0003_property_latitude_property_longitude	2026-04-27 21:28:54.549598+00
26	properties	0007_merge_20260308_1810	2026-04-27 21:28:54.550194+00
27	comunication	0001_initial	2026-04-27 21:28:54.574847+00
28	properties	0008_alter_property_options_savedproperty	2026-04-27 21:28:54.587045+00
29	properties	0009_alter_property_image_url	2026-04-27 21:28:54.590502+00
30	properties	0010_delete_booking	2026-04-27 21:28:54.59176+00
31	properties	0011_remove_property_active_listing_remove_property_state_and_more	2026-04-27 21:28:54.599757+00
32	sessions	0001_initial	2026-04-27 21:28:54.604809+00
33	transactions	0001_initial	2026-04-27 21:28:54.616283+00
34	transactions	0002_initial	2026-04-27 21:28:54.64235+00
35	transactions	0003_booking	2026-04-27 21:28:54.653028+00
36	transactions	0004_purchaserequest	2026-04-27 21:28:54.669661+00
37	transactions	0005_booking_updated_at	2026-04-27 21:28:54.676555+00
38	transactions	0006_remove_rentalapplication_applicant_and_more	2026-04-27 21:28:54.701456+00
39	users	0002_alter_client_id_alter_owner_id_alter_user_id	2026-04-27 21:28:54.793561+00
40	users	0003_alter_client_id_alter_owner_id_alter_user_id	2026-04-27 21:28:54.885552+00
41	properties	0012_alter_property_price	2026-05-08 20:59:00.935016+00
42	aichat	0001_initial	2026-05-10 20:36:41.374687+00
43	transactions	0007_purchase_delete_contract	2026-05-11 21:09:21.385635+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
033ckybgaixodp3tmfbi27f34aqs4ysm	.eJxVjEEOwiAQRe_C2hAGCowu3fcMzQwMUjVtUtqV8e7apAvd_vfef6mBtrUOW5NlGLO6KOjU6XdkSg-ZdpLvNN1mneZpXUbWu6IP2nQ_Z3leD_fvoFKr37pDxsjORUgYnU8Bkg3kBbwwkkEAPsfoDXmbCggFilmKQbaWHZag3h_wZTfS:1wMmWw:2jxTl06MFE8vMyVdtvlWTyKBtkMl8uDaORdvM3OONRw	2026-05-26 12:48:10.441178+00
8pwtwz6ualmn7ex84fttx1yexf2hrz15	.eJxVjMsOwiAQAP-FsyG8ttt69N5vaNgFpGogKe3J-O-GpAe9zkzmLRZ_7Hk5WtyWNYir0CAuv5A8P2PpJjx8uVfJtezbSrIn8rRNzjXE1-1s_wbZt9y_NBGASonRaiQV9ICOicEyp5gUTsojeDIOOAwjWHLWkNYWIjocjfh8ARIPN8o:1wPRO8:KXAWqqR5JeQo7IYU2hilprzQ2E1u5Fxox7yvo0c-PJE	2026-06-02 20:50:04.900965+00
0u9sw160b8cvj2k77sz1t1z2wqqhmtqt	.eJxVjMEOwiAQRP-FsyGwC7R49N5vIAtLpGogKe3J-O-2SQ-auc17M28RaFtL2HpewsziKjSIy28ZKT1zPQg_qN6bTK2uyxzlociTdjk1zq_b6f4dFOplX3twyiRj8-iQko3RDMrRQA4TOt6jGWBE1Nl5tp4BCTyzQgsRvc3i8wXpLTdD:1wMogH:kkAGagRU8I-8owiqijUUafyhZEIAO8TxTBNrqL7wMdc	2026-05-26 15:05:57.15977+00
jqwydvu8iwnfxrveucxhkc0x84kfyu72	.eJxVjLEOwjAMRP8lM4pqB0LCyN5vqBzbIQXUSk07If4dInWA5YZ77-5lBtrWMmxVl2EUczHOHH67RPzQqQG503SbLc_TuozJNsXutNp-Fn1ed_fvoFAtbe2jsACmHEQQOlQAjyGJetKcPAvHb0Jmd8zqOnYxhBMhAJ0RIZj3BxHrOIQ:1wMaK5:e9GPC0tt7UwvCEB2ICNC-4D98_PHCrvznslIsvusNsA	2026-05-25 23:46:05.456667+00
oqgi3guj7nelpyfujku2fag57lnon2ti	.eJxVjM0OwiAQhN-FsyEsP1v06N1nIAssUjU0Ke3J-O62SQ96mmS-b-YtAq1LDWvnOYxZXASI028XKT257SA_qN0nmaa2zGOUuyIP2uVtyvy6Hu7fQaVet7ViVDAgWjDWMunkbPGQEZU7gy3aKKRkOEJWCTw5U7YwGpWFVAb24vMFr1k2yg:1wMaKJ:tfDxwkgZAe9WGQFfYD6_7yb2SZ_YTazIze2dRR1aP0I	2026-05-25 23:46:19.549376+00
\.


--
-- Data for Name: properties_property; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.properties_property (id, title, description, address, city, price, listing_type, rooms, bathrooms, square_meters, capacity, image, image_url, created_at, owner_id, availability_dates, latitude, longitude) FROM stdin;
7	Escapada con estilo a Santa Teresita – Corazón de Cali	Descubre la comodidad y el estilo en este apartamento de una habitación con dos camas, ubicado en el exclusivo barrio Santa Teresita, en Cali. Con una decoración moderna y acogedora, es el espacio perfecto tanto para viajes de descanso como de negocios.	Santa Teresita, Comuna 2, Cali ciudad, Cali, Sur, Valle del Cauca, RAP Pacífico, Colombia	Cali ciudad	294	short_term	1	1	50	4	properties/ac92e3ea-525d-48ad-8965-b35b18b4684c.jpeg.avif		2026-03-25 05:34:45.86+00	5		3.452401	-76.547703
6	Cabaña de lujo con jacuzzi Malbec-La Cava Lodge	Ubicada en el majestuoso bosque de Santa Elena, esta cabaña rústica moderna fusiona lo mejor de la tradición y el diseño contemporáneo. Construida con materiales naturales como madera y piedra, ofrece un ambiente cálido y acogedor, mientras que sus amplios ventanales permiten disfrutar del paisaje. Ideal para desconectar, brindando una experiencia única de tranquilidad y confort en la naturaleza. Un refugio perfecto para quienes buscan escapar y relajarse en armonía con el entorno.	Parque Arví, Calle 86, Piedras Blancas - Matasano, Santa Elena, Medellín, Valle de Aburrá, Antioquia, RAP del Agua y la Montaña, 050017, Colombia	Medellín	3000000	long_term	1	1	60	2	properties/2ed504cc-918b-4d3d-b4fe-90350ec47ad9_9mD4fAg.jpeg.avif		2026-03-25 05:32:51.086+00	5		6.281397	-75.502688
5	Hotel/Aeropuerto/Desayuno/Embajada/T. Buses/AV 26	El espacio está ubicado en un rango de 10 a 15 minutos de sitios como el aeropuerto, el centro histórico, la embajada americana, el jardín botánico, la Virgilio Barco, varios parques recreativos y centros comerciales. El lugar cuenta con una zona común amplia y una elegante recepción. Cada habitación es completamente privada con su respectivo baño y dotadas de todas las comodidades. Contamos con un personal muy servicial y atento a responder cualquiera de sus inquietudes.	Fontibón, UPZs de Bogotá, Localidad Fontibón, Bogotá, Bogotá, Distrito Capital, RAP (Especial) Central, 110921, Colombia	Bogotá	154	short_term	1	1	73	2	properties/a017ff3c-0921-41e0-82a2-44cce40f3e3d.jpeg.avif		2026-03-25 05:29:59.236+00	5		4.673294	-74.144746
1	Acogedora Suite, vista al océano en Cartagena 921	Espléndido apartamento en Cartagena frente al mar, Vista privilegiada a las playa, te podrás relajar escuchando las olas y sintiendo la brisa del mar. Vive una experiencia única en clima cálido y perfecto para vacaciones o viaje de negocios.\r\nEl apartamento cuenta con amplia cocina, cama king, espacio cómodos y confortables. El conjunto ofrece dos piscinas al aire libre, jacuzzi, zonas húmedas con turco y áreas comunes diseñadas para el descanso. Todo para que tu estadía sea inolvidable.	Cartagena de Indias, Dique, Bolívar, RAP Caribe, Colombia	Cartagena de Indias	1000000	sale	1	1	79	2	properties/cd37a21e-766a-45d5-9112-2e46d43bb919.jpeg.avif		2026-03-21 03:04:35.705+00	6		10.426557	-75.544167
4	Casa Serena	Loft moderno con jacuzzi climatizado y vista panorámica a Medellín. Diseño elegante, privacidad total y naturaleza a solo 25 min del Poblado.	Comuna 14 - El Poblado, Perímetro Urbano Medellín, Medellín, Valle de Aburrá, Antioquia, RAP del Agua y la Montaña, Colombia	Perímetro Urbano Medellín	1168000	sale	1	1	83	2	properties/02268d9a-99f6-4ef8-a65d-bd8a2942fe05.jpeg.avif		2026-03-24 03:56:22.796+00	6		6.200620	-75.563683
3	Cabaña F2 Rodadero S. Marta	Relájate con toda la familia en este alojamiento donde vas a estar tranquilo, cómodo ,dónde cada detalle de esta cabaña fue diseñado para ti, para que te sientas como en casa;  cuando regreses al Rodadero vas a querer repetir la experiencia de ser nuestro huésped y nos vas a súper recomendar con tus amigos, familiares y conocidos, Estamos ubicados a solo 300 metros de la playa del Rodadero , cerca al centro comercial Arrecife, supermercados Olímpica y D1.	Perímetro Urbano Santa Marta, Santa Marta, Magdalena, RAP Caribe, Colombia	Perímetro Urbano Santa Marta	700	short_term	3	2	100	1	properties/6c64ca3c-b5c9-4f26-9ba6-b9f73bafe4bf.png.avif		2026-03-22 04:45:12.82+00	6		11.232094	-74.195092
2	cogedora Suite, vista al océano en Cartagena 921	Espléndido apartamento en Cartagena frente al mar, Vista privilegiada a las playa, te podrás relajar escuchando las olas y sintiendo la brisa del mar. Vive una experiencia única en clima cálido y perfecto para vacaciones o viaje de negocios.\r\nEl apartamento cuenta con amplia cocina, cama king, espacio cómodos y confortables. El conjunto ofrece dos piscinas al aire libre, jacuzzi, zonas húmedas con turco y áreas comunes diseñadas para el descanso. Todo para que tu estadía sea inolvidable.	Cartagena de Indias, Dique, Bolívar, RAP Caribe, Colombia	Cartagena de Indias	691	short_term	1	1	73	2	properties/6d80a694-d918-4f55-8f7d-767a64811a43.png.avif		2026-03-22 04:30:26.176+00	6		10.426557	-75.544167
12	Apt Moderno |A pie Zona Rosa, Cafés y Restaurantes	Apartamento con estilo ideal para la diversión, el trabajo remoto y el descanso, en la zona más turística y central de Pereira. A dos cuadras de la Av. Circunvalar\r\n\r\n✪ Check-in autónomo\r\n✪ Espacio de trabajo con internet de alta velocidad\r\n✪ Cerca de restaurantes\r\n✪ La mejor vida nocturna, bares y discotecas\r\n✪ Centros comerciales\r\n✪ Bancos\r\n✪ Supermercados\r\n\r\n✪ Aire acondicionado	Dosquebradas, Risaralda, RAP Eje Cafetero, Colombia	Dosquebradas	110	short_term	2	1	84	4	properties/737d9ae0-564a-4dd7-b4f2-4e41c267aef0.jpeg.avif		2026-03-25 05:47:55.259+00	1		4.833955	-75.671301
11	Apartamento nuevo tipo loft #8 cabecera	Moderno apartamento  en altos de cabecera, cerca de universidades y centros comerciales, ideal para descansar, trabajar o turistear, cuenta con una habitación con cama queen, sabanas 300 hilos, aire acondicionado, sala con cama doble y sofa cama, ventilador, cocina equipada, zona de trabajo, sala con tv. Area comun acceso a terraza, lavandería, parqueadero no cubierto,  maquina dispensadora de snack y bebidas. Cerradura digital. Bienvenidos!	La Concordia, San Miguel, Comuna 6 - La Concordia, Perímetro Urbano Bucaramanga, Bucaramanga, Metropolitana, Santander, RAP Gran Santander, 680003, Colombia	Perímetro Urbano Bucaramanga	800000000	sale	1	1	107	5	properties/8a7700cd-1892-4ea7-bb12-0cc4fdcb6d2b.jpeg.avif		2026-03-25 05:45:36.615+00	1		7.112534	-73.119156
8	D603-Estudio Con Excelente Ubicación	Hermoso estudio con todas las comodidades para sus vacaciones o viaje de negocios. Ubicado sobre la via principal de Barranquilla, con fácil desplazamiento a cualquier punto de la ciudad.  Estámoa situados a solo 5 minutos de centros comerciales, restaurantes, y bancos. El edificio cuenta con lobby, parqueadero, salas de coworking, Salón de juegos y TV, Gimnasio,  jacuzzi y vigilancia las 24 horas.  Para su comodidad ofrecemos servicio de mini bar por un costo adicional.	Parque Venezuela, La Campiña, Localidad Norte - Centro Histórico, Perímetro Urbano Barranquilla, Barranquilla, Atlántico, Colombia	Perímetro Urbano Barranquilla	1200000	sale	1	1	73	3	properties/623b9148-235e-4fe3-ac62-cbc6c08b2d3e.jpeg.avif		2026-03-25 05:38:23.851+00	5		11.001456	-74.824172
9	Atardecer llanero	Disfruta tu estadía en un apartamento con piscina, cancha de fútbol, parque infantil y rutas para caminar. Frente al centro comercial Rosa Blanca y cerca a Capachos. Desde el apartamento podrás admirar las hermosas vistas del atardecer llanero.	Soceagro Airport, Villanueva, Casanare, RAP Llanos, Colombia	Villanueva	352	short_term	3	2	105	6	properties/88f62f10-a42e-49b5-970f-652baf1b94d8.png.avif		2026-03-25 05:40:57.656+00	1		4.484565	-72.824114
10	Aparta Hotel en San Gil	Aparta Hotel dentro del centro comercial San Gil Plaza, dispone de piscina, sauna, turco. Además de que el centro comercial dispone de supermercado, zona de comidas, cafetería, cine, etc.	San Gil, Guanentá, Santander, RAP Gran Santander, Colombia	San Gil	2000000	long_term	1	2	96	5	properties/2ed504cc-918b-4d3d-b4fe-90350ec47ad9.jpeg.avif		2026-03-25 05:43:04.276+00	1		6.555286	-73.131235
\.


--
-- Data for Name: properties_savedproperty; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.properties_savedproperty (id, created_at, property_obj_id, user_id) FROM stdin;
\.


--
-- Data for Name: transactions_booking; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.transactions_booking (id, check_in, check_out, status, created_at, property_id, user_id, updated_at) FROM stdin;
50	2026-05-19	2026-05-22	pending	2026-05-19 20:47:42.921005+00	12	15	2026-05-19 20:47:42.921014+00
51	2026-05-19	2026-06-18	pending	2026-05-19 20:50:51.043284+00	10	15	2026-05-19 20:50:51.043292+00
\.


--
-- Data for Name: transactions_purchase; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.transactions_purchase (id, created_at, updated_at, total_value, status, buyer_id, property_id) FROM stdin;
4	2026-05-19 20:38:56.067825+00	2026-05-19 20:38:56.067845+00	800000000.00	pending	15	11
\.


--
-- Data for Name: users_client; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.users_client (id, user_id) FROM stdin;
1	6
2	8
\.


--
-- Data for Name: users_owner; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.users_owner (id, user_id) FROM stdin;
1	5
5	17
6	18
\.


--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.users_user (id, password, last_login, is_superuser, first_name, last_name, is_staff, is_active, date_joined, email, phone, registration_date) FROM stdin;
17	pbkdf2_sha256$1200000$O4jXTmsjWdytLxrifcAaVS$qhMRvVpqz6QmZilJKSuLlaEgvY06hmJyJ4ZYAXXOQFw=	2026-05-19 20:35:43.762624+00	f	Laura	Marin	f	t	2026-05-19 20:34:49.158093+00	lmarinvelez0@gmail.com	3045676451	2026-05-19 20:34:49.314725+00
5	pbkdf2_sha256$1200000$IJ7w6VGD2xJ3W3UxWtc0Y4$3+nG5EN6DG95ZPxfN/urUxCFMK1neK8KlBZOpAAt6vc=	2026-05-10 04:47:05.919+00	f	mateo	cadavid	f	t	2026-03-21 03:03:06.229+00	cadavidmateo90@gmail.com	3237982909	2026-03-21 03:03:06.446+00
6	pbkdf2_sha256$1200000$6hsBUMC8hdCUrnPukyViGG$Pp7zrYsBrTAA0VYrD6FtJ9BxFbrdzsat9hZna0mpqOs=	2026-05-11 22:42:27.829+00	f	kevin	quiceno	f	t	2026-03-21 03:06:49.653+00	kevinplaythings@gmail.com	3237982909	2026-03-21 03:06:49.841+00
7	pbkdf2_sha256$1200000$JuARaVoC8q2hVsuBKOkga6$WJDV5oR3o3Tgwslq1yIMGlUC5lGpuhnmq/jtpVJ+/u8=	2026-03-25 01:19:34.875+00	t	mateo	cadavid	t	t	2026-03-25 01:18:48.244+00	cadavidmateo9@gmail.com	\N	2026-03-25 01:18:48.407+00
8	pbkdf2_sha256$1200000$zNPGzMaBeKA10kdKjqsB9i$6HaELL1LyOPlhORtggDvdAFm3MivmyDmeVjcuNKw7s8=	2026-05-10 04:45:58.694+00	f	Sarah	Leon	f	t	2026-05-10 04:45:49.457+00	ssleona@gmail.com	3193902463	2026-05-10 04:45:49.654+00
18	pbkdf2_sha256$1200000$QmDnhh53Y3Npf0a3pEB3gs$LIoSBltWdITyps4gvyX7OW6noukLw7lAAuNCz8ErQCo=	\N	f	Jeronimo	Gomez	f	t	2026-05-19 20:44:30.590391+00	jeronimo@hotmail.com	3134567687	2026-05-19 20:44:30.753608+00
15	pbkdf2_sha256$1200000$au38owAIS5MIs0hc5v5QAb$3ZEaWwsycy1XoXi1fWD+rbP+1io8QWSCLjI7ovKt/2E=	2026-05-19 20:45:23.989703+00	t	laura	marin	t	t	2026-05-19 20:22:28.430808+00	lauramarin@gmail.com	\N	2026-05-19 20:22:28.584576+00
\.


--
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.users_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: usuario_django
--

COPY public.users_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: aichat_assistantmessage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.aichat_assistantmessage_id_seq', 20, true);


--
-- Name: aichat_assistantsession_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.aichat_assistantsession_id_seq', 2, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: comunication_conversation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.comunication_conversation_id_seq', 4, true);


--
-- Name: comunication_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.comunication_message_id_seq', 3, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 27, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 43, true);


--
-- Name: properties_property_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.properties_property_id_seq', 14, true);


--
-- Name: properties_savedproperty_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.properties_savedproperty_id_seq', 5, true);


--
-- Name: transactions_booking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.transactions_booking_id_seq', 51, true);


--
-- Name: transactions_purchase_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.transactions_purchase_id_seq', 4, true);


--
-- Name: users_client_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.users_client_id_seq', 5, true);


--
-- Name: users_owner_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.users_owner_id_seq', 6, true);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, false);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.users_user_id_seq', 18, true);


--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: usuario_django
--

SELECT pg_catalog.setval('public.users_user_user_permissions_id_seq', 1, false);


--
-- Name: aichat_assistantmessage aichat_assistantmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.aichat_assistantmessage
    ADD CONSTRAINT aichat_assistantmessage_pkey PRIMARY KEY (id);


--
-- Name: aichat_assistantsession aichat_assistantsession_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.aichat_assistantsession
    ADD CONSTRAINT aichat_assistantsession_pkey PRIMARY KEY (id);


--
-- Name: aichat_assistantsession aichat_assistantsession_session_id_key; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.aichat_assistantsession
    ADD CONSTRAINT aichat_assistantsession_session_id_key UNIQUE (session_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: comunication_conversation comunication_conversation_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.comunication_conversation
    ADD CONSTRAINT comunication_conversation_pkey PRIMARY KEY (id);


--
-- Name: comunication_message comunication_message_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.comunication_message
    ADD CONSTRAINT comunication_message_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: properties_property properties_property_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.properties_property
    ADD CONSTRAINT properties_property_pkey PRIMARY KEY (id);


--
-- Name: properties_savedproperty properties_savedproperty_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.properties_savedproperty
    ADD CONSTRAINT properties_savedproperty_pkey PRIMARY KEY (id);


--
-- Name: transactions_booking transactions_booking_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.transactions_booking
    ADD CONSTRAINT transactions_booking_pkey PRIMARY KEY (id);


--
-- Name: transactions_purchase transactions_purchase_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.transactions_purchase
    ADD CONSTRAINT transactions_purchase_pkey PRIMARY KEY (id);


--
-- Name: comunication_conversation unique_conversation_per_property_and_buyer; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.comunication_conversation
    ADD CONSTRAINT unique_conversation_per_property_and_buyer UNIQUE (property_id, buyer_id);


--
-- Name: properties_savedproperty unique_saved_property_per_user; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.properties_savedproperty
    ADD CONSTRAINT unique_saved_property_per_user UNIQUE (user_id, property_obj_id);


--
-- Name: users_client users_client_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.users_client
    ADD CONSTRAINT users_client_pkey PRIMARY KEY (id);


--
-- Name: users_client users_client_user_id_key; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.users_client
    ADD CONSTRAINT users_client_user_id_key UNIQUE (user_id);


--
-- Name: users_owner users_owner_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.users_owner
    ADD CONSTRAINT users_owner_pkey PRIMARY KEY (id);


--
-- Name: users_owner users_owner_user_id_key; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.users_owner
    ADD CONSTRAINT users_owner_user_id_key UNIQUE (user_id);


--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: aichat_assi_session_1fcf0b_idx; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX aichat_assi_session_1fcf0b_idx ON public.aichat_assistantmessage USING btree (session_id, created_at);


--
-- Name: aichat_assistantmessage_session_id_ffa512e5; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX aichat_assistantmessage_session_id_ffa512e5 ON public.aichat_assistantmessage USING btree (session_id);


--
-- Name: aichat_assistantsession_user_id_f5efd82c; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX aichat_assistantsession_user_id_f5efd82c ON public.aichat_assistantsession USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: comunication_conversation_buyer_id_0149d133; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX comunication_conversation_buyer_id_0149d133 ON public.comunication_conversation USING btree (buyer_id);


--
-- Name: comunication_conversation_owner_id_f0144a24; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX comunication_conversation_owner_id_f0144a24 ON public.comunication_conversation USING btree (owner_id);


--
-- Name: comunication_conversation_property_id_e014866c; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX comunication_conversation_property_id_e014866c ON public.comunication_conversation USING btree (property_id);


--
-- Name: comunication_message_conversation_id_75d6c201; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX comunication_message_conversation_id_75d6c201 ON public.comunication_message USING btree (conversation_id);


--
-- Name: comunication_message_sender_id_deee391b; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX comunication_message_sender_id_deee391b ON public.comunication_message USING btree (sender_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: properties_property_owner_id_6700dc90; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX properties_property_owner_id_6700dc90 ON public.properties_property USING btree (owner_id);


--
-- Name: properties_savedproperty_property_obj_id_028e5297; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX properties_savedproperty_property_obj_id_028e5297 ON public.properties_savedproperty USING btree (property_obj_id);


--
-- Name: properties_savedproperty_user_id_07073967; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX properties_savedproperty_user_id_07073967 ON public.properties_savedproperty USING btree (user_id);


--
-- Name: transactions_booking_property_id_ca80643a; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX transactions_booking_property_id_ca80643a ON public.transactions_booking USING btree (property_id);


--
-- Name: transactions_booking_user_id_469936a8; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX transactions_booking_user_id_469936a8 ON public.transactions_booking USING btree (user_id);


--
-- Name: transactions_purchase_buyer_id_224c779c; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX transactions_purchase_buyer_id_224c779c ON public.transactions_purchase USING btree (buyer_id);


--
-- Name: transactions_purchase_property_id_75791310; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX transactions_purchase_property_id_75791310 ON public.transactions_purchase USING btree (property_id);


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: usuario_django
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: aichat_assistantmessage aichat_assistantmess_session_id_ffa512e5_fk_aichat_as; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.aichat_assistantmessage
    ADD CONSTRAINT aichat_assistantmess_session_id_ffa512e5_fk_aichat_as FOREIGN KEY (session_id) REFERENCES public.aichat_assistantsession(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aichat_assistantsession aichat_assistantsession_user_id_f5efd82c_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.aichat_assistantsession
    ADD CONSTRAINT aichat_assistantsession_user_id_f5efd82c_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comunication_conversation comunication_convers_property_id_e014866c_fk_propertie; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.comunication_conversation
    ADD CONSTRAINT comunication_convers_property_id_e014866c_fk_propertie FOREIGN KEY (property_id) REFERENCES public.properties_property(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comunication_conversation comunication_conversation_buyer_id_0149d133_fk; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.comunication_conversation
    ADD CONSTRAINT comunication_conversation_buyer_id_0149d133_fk FOREIGN KEY (buyer_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comunication_conversation comunication_conversation_owner_id_f0144a24_fk; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.comunication_conversation
    ADD CONSTRAINT comunication_conversation_owner_id_f0144a24_fk FOREIGN KEY (owner_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comunication_message comunication_message_conversation_id_75d6c201_fk_comunicat; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.comunication_message
    ADD CONSTRAINT comunication_message_conversation_id_75d6c201_fk_comunicat FOREIGN KEY (conversation_id) REFERENCES public.comunication_conversation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comunication_message comunication_message_sender_id_deee391b_fk; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.comunication_message
    ADD CONSTRAINT comunication_message_sender_id_deee391b_fk FOREIGN KEY (sender_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: properties_property properties_property_owner_id_6700dc90_fk; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.properties_property
    ADD CONSTRAINT properties_property_owner_id_6700dc90_fk FOREIGN KEY (owner_id) REFERENCES public.users_owner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: properties_savedproperty properties_savedprop_property_obj_id_028e5297_fk_propertie; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.properties_savedproperty
    ADD CONSTRAINT properties_savedprop_property_obj_id_028e5297_fk_propertie FOREIGN KEY (property_obj_id) REFERENCES public.properties_property(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: properties_savedproperty properties_savedproperty_user_id_07073967_fk; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.properties_savedproperty
    ADD CONSTRAINT properties_savedproperty_user_id_07073967_fk FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transactions_booking transactions_booking_property_id_ca80643a_fk_propertie; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.transactions_booking
    ADD CONSTRAINT transactions_booking_property_id_ca80643a_fk_propertie FOREIGN KEY (property_id) REFERENCES public.properties_property(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transactions_booking transactions_booking_user_id_469936a8_fk; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.transactions_booking
    ADD CONSTRAINT transactions_booking_user_id_469936a8_fk FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transactions_purchase transactions_purchas_property_id_75791310_fk_propertie; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.transactions_purchase
    ADD CONSTRAINT transactions_purchas_property_id_75791310_fk_propertie FOREIGN KEY (property_id) REFERENCES public.properties_property(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: transactions_purchase transactions_purchase_buyer_id_224c779c_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.transactions_purchase
    ADD CONSTRAINT transactions_purchase_buyer_id_224c779c_fk_users_user_id FOREIGN KEY (buyer_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_client users_client_user_id_06d1c832_fk; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.users_client
    ADD CONSTRAINT users_client_user_id_06d1c832_fk FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_owner users_owner_user_id_e6b855b1_fk; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.users_owner
    ADD CONSTRAINT users_owner_user_id_e6b855b1_fk FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk; Type: FK CONSTRAINT; Schema: public; Owner: usuario_django
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict cu0DgKDOSWUUdckZ0ATXIM5uGx3PYodiIEUiJa2e7gS1gHAj4pAixDeZ77Wlqyv

