# Generated by Django 6.0.3 on 2026-03-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="availability_dates",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
