# Generated by Django 6.0.3 on 2026-03-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_latitude_property_longitude'),
        ('properties', '0006_rename_date_availability_availability_dates_and_more'),
    ]

    operations = [
    ]
