# Generated by Django 6.0.3 on 2026-03-23 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0009_alter_property_image_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
