# Generated by Django 5.2.6 on 2026-03-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='active_listing',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
