# Generated by Django 5.2.6 on 2026-03-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_booking_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalapplication',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='rentalapplication',
            name='property',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='application',
        ),
        migrations.DeleteModel(
            name='PurchaseRequest',
        ),
        migrations.DeleteModel(
            name='RentalApplication',
        ),
    ]
