# Generated by Django 6.0.2 on 2026-03-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_alter_propiedad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
