# Generated by Django 6.0.2 on 2026-03-03 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_alter_propiedad_id'),
        ('usuarios', '0005_alter_cliente_id_alter_propietario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='banos',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='habitaciones',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='metros_cuadrados',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='usuarios.propietario'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado')], default='disponible', max_length=20),
        ),
    ]
