# Generated by Django 6.0.2 on 2026-03-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0006_propiedad_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='capacidad_personas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
