# Generated by Django 6.0.2 on 2026-03-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0007_propiedad_capacidad_personas'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='tipo_publicacion',
            field=models.CharField(choices=[('short_term', 'Short-term rental'), ('long_term', 'Long-term rental'), ('sale', 'Sale')], default='short_term', max_length=20),
        ),
    ]
